### ISSUE TITLE
new maintainership

### ISSUE THREAD

**Issue by goolord** [neovimhaskell/haskell-vim#122]
It doesn't seem like there's been any maintainer activity for 3 years. Considering this is ostensibly the most popular Haskell ftplugin, it's a sad state. I would be happy to take up maintainership if there's no other interest.

(cc'ing neovimhaskell organization members who are still active on github)
@osa1 @tek @jacobstanley @saep

**Comment by tek** [comment]
do you have any specific plans?

**Comment by tek** [comment]
well I have no rights in this project, but you have my vote :upside_down_face:

**Comment by raichoo** [comment]
Just merged most of the stuff.
