### ISSUE TITLE
haskell_indent_if not lining up if statement?

### ISSUE THREAD

**Issue by wscarter** [neovimhaskell/haskell-vim#14]
I set this variable to 3 in the vimrc but am getting this behavior:

![screen shot 2015-01-29 at 3 31 58 pm](https://cloud.githubusercontent.com/assets/3280824/5966677/21c337fc-a7cc-11e4-806a-299ddaffc58c.png)

Is this a common issue?

**Comment by raichoo** [comment]
Sorry, I cannot reproduce this :/

**Comment by aerohit** [comment]
Indentation doesn't work for me either. I have copied the values exactly as they are in the readme.

**Comment by raichoo** [comment]
The Readme was a little misleading about editing the `.vimrc` I've moved the needed configuration into the `pathogen` section. Please check if you have

    syntax on
    filetype on
    filetype plugin indent on

in your `.vimrc`. Preferably directly after `pathogen#infect()`.
If this does not work I presume that there is something wrong with your vim setup.

Kind regards,
raichoo

**Comment by aerohit** [comment]
Hey Raichoo,

Thanks a lot for getting back man. I use Vundle to install packages. But I have the three settings (about syntax and filetype) exactly as you have suggested. But it still doesn't work.

It's a pity, because your plugin looks very promising.

Regards,
Rohit

**Comment by raichoo** [comment]
I think a good way to find the problem would be to start with an empty `.vimrc` and build up from there. Something seems to interfere. Try it without the indentation settings etc. Maybe something is going wrong there. I'd really like to know the reason why this happens.

Kind regards, raichoo

**Comment by aerohit** [comment]
Hey man,

I tried by starting from an empty .vimrc and carefully adding back stuff without any success. 

During the weekend I decided to try out neovim, changed my plugin manager from Vundle to vim-plug and also removed a lot of cruft from my vimrc. I installed haskell-vim and it just worked. I don't know if the problem was with Vundle or vimrc.

The plugin works like a charm, thanks a lot for writing it.

Regards,
Rohit

**Comment by raichoo** [comment]
Ah nice, another neovim convert :) I did the switch some time ago, but test the plugin in both.

Glad you like it. I'll leave this issue open in case @paperziggurat has some findings to report.

Kind regards,
raichoo

**Comment by Ancipital** [comment]
I'm using:
    % vim --version
    VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Dec  2 2014 16:26:07)
    Included patches: 1-273
    Modified by Gentoo-7.4.273

I'm using pathogen and ... it's not working for me either. The only file I modified was .vimrc per your suggestions. I have no idea what else to say here, feel free to ask questions.

**Comment by Ancipital** [comment]
I've installed nvim now but unfortunately it doesn't work for me there either.

I do some simple testing, like `foobarfoo x = if x > 5`. Then I hit enter... nothing gets aligned. Bit annoyed by vim, don't take it personal :laughing:

**Comment by raichoo** [comment]
I'm out of ideas what causes this. You might want to check with my `.nvimrc` if I'm doing something in there that might be missing.

https://github.com/raichoo/rcfiles/blob/master/nvimrc

Kind regards,
raichoo

**Comment by rramsden** [comment]
If anyone else is having indent issues check your indentexpr `:set indentexpr` make sure its using the expression defined in the haskell-vim `indentexpr=GetHaskellIndent()`.

My issue was I had vim2hs installed alongside haskell-vim which overrided the indent expression.

**Comment by raichoo** [comment]
Ah! Finally someone with a clue of what's going on :D. Hopefully this will solve the issue.
