### ISSUE TITLE
indent bug when instantiating records

### ISSUE THREAD

**Issue by mikebenfield** [neovimhaskell/haskell-vim#32]
The comma is indented correctly for this code:
```
SomeRecord { name = "a"
           ,
```
but not for this code:
```
SomeRecord { name = ")"
,
```

**Comment by raichoo** [comment]
Yeah I see where this is coming from… That will be quite tricky to fix. I'll leave this open until I find a satisfying solution. Since Vim does all of this with Regex I doubt that there will be a 100% solution for this. But yeah, it's pretty annoying…

**Comment by raichoo** [comment]
This should be fixed now.
