### ISSUE TITLE
Highlighting for class methods broken with one of the recent commits

### ISSUE THREAD

**Issue by osa1** [neovimhaskell/haskell-vim#44]
See the screenshot below, broken one is after a git pull. (unfortunately I lost my terminal history so can't tell which commits were pulled)
![vim-hs-syntax-err](https://cloud.githubusercontent.com/assets/448274/8965243/3547e808-35f8-11e5-898a-1985cdbac270.png)

(shiwSecond method isn't highligted)

**Comment by raichoo** [comment]
I know what causes this. Need some time to think about the fix though.

**Comment by raichoo** [comment]
Should work now.

**Comment by osa1** [comment]
Yes! Thanks!
