### ISSUE TITLE
CPP macros aren't highlighted in some cases

### ISSUE THREAD

**Issue by osa1** [neovimhaskell/haskell-vim#49]
For example, if it follows directly after an import statement, it's not highlighted properly:

```haskell
import Control.Monad
#include "Blah.h"
```

but this works:

```haskell
import Control.Monad
f = blah
#include "Blah.h"
```

**Comment by raichoo** [comment]
I simplified a lot of things. The big problems was that I was trying to handle lots of different kinds of blocks, I removed this for now until I find a more satisfying approach to do this. This results in `where` and `let` getting highlighted differently now but it's somewhat more consistent.
