### ISSUE TITLE
Why are so many of the highlighting links arbitrary?

### ISSUE THREAD

**Issue by johntyree** [neovimhaskell/haskell-vim#52]
I really like the way indentation works with this, but I don't understand the syntax highlighting at all.

A large number of the highlighting links seem to be completely arbitrarily chosen.

It would be a lot more sensible to link syntax features to their semantic equivalents so that colors schemes will behave correctly and intuition about the meaning of colors will remain portable across languages.

Some examples that don't make any sense to me:
```
highlight def link haskellQuotedType Include
highlight def link haskellType Include
...
highlight def link haskellImportKeywords Structure
highlight def link haskellDeclKeyword Structure
highlight def link haskellDecl Structure
highlight def link haskellWhere Structure
highlight def link haskellLet Structure
```

Why aren't types linked to `Type`, normal keywords linked to `Keyword` and import keywords linked to `Import`?

I can always fork this and change things of course, but I'm wondering if there's some secret benefit to doing it this way that I've missed.

**Comment by johntyree** [comment]
We discussed this in the PR. Closing.

**Comment by jystic** [comment]
I just want to add that this is the reason I don't use `haskell-vim`

I write code in other languages too and I find it too difficult to get a pleasing color scheme across all of them when I use this syntax file.

**Comment by jystic** [comment]
I have considered manually rewiring all of the highlight links in my vimrc because I quite like the actual tokenization that you do :+1:

**Comment by raichoo** [comment]
I'd be perfectly happy to accept different highlight links that can be toggled by a flag. The Emacs Agda mode has a flag to support Conor's taste and I'd be willing to accept something like that.

**Comment by raichoo** [comment]
I've introduced a flag to activate another highlighting in PR #63.
