### ISSUE TITLE
String escapes mess up the highlighting

### ISSUE THREAD

**Issue by rubik** [neovimhaskell/haskell-vim#57]
Example:
```haskell
putStrLn "test \"substring\" test" -- haskell-vim continues to highlight as if the string never closed
```

haskell-vim correctly ignores the first escape, but treats the second as string terminating. What's also wrong is that by default string highlighting continues even after a newline, while this should be the case only with a multiline string.

It appears that escaped double quotes are misinterpreted only when they are preceded by a letter. In the example above, only the second one is preceded by a letter and interpreted as a string-terminating quote.

**Comment by raichoo** [comment]
I cannot reproduce this. On my machine. Maybe there is some other plugin or setting interfering?

**Comment by rubik** [comment]
You were right. It was Rykka/clickable.vim, which I promptly removed. Sorry for not checking other plugins.

**Comment by raichoo** [comment]
No problem. Thanks for reporting it.
