### ISSUE TITLE
multiline comment syntax highlighting

### ISSUE THREAD

**Issue by akhileshs** [neovimhaskell/haskell-vim#58]
I'm using haskell-vim-now (https://github.com/begriffs/haskell-vim-now) as my IDE for writing Haskell and I'm told that it uses this package for syntax highlighting.
![1](https://cloud.githubusercontent.com/assets/7877428/11914389/f169f454-a6a5-11e5-843d-afcf2d831706.png)

I noticed that multi-line comments don't get syntax highlighting as shown above. Any help would be appreciated!

Thanks,
Akhilesh Srikanth

**Comment by raichoo** [comment]
I cannot reproduce this. I'm not using `haskell-vim-now` so I guess it's a problem over there.

**Comment by akhileshs** [comment]
Cool, good to know.

**Comment by matijaSos** [comment]
> For future reference, there is a conflict with the 'rainbow-parentheses' plugin. Disabling it on haskell source files fixed this specific issue.

Thank you @freuk, you saved me, never would have thought of this!

**Comment by peri4n** [comment]
@freuk You saved me countless hours man. Thank you very much.
