### ISSUE TITLE
'in' decreases indent as first characters of name

### ISSUE THREAD

**Issue by shanemikel** [neovimhaskell/haskell-vim#59]
When using 'in' as the first two letters of a variable name (outside of a let/in expression) decreases indent without correcting when a third letter is typed.

To reproduce, try typing this.

    f x = x'
        where x'  = x * 2
              ini = "something"

You will see typing the first two letters of the name 'ini' will cause the indent to be decreased (I assume it is assuming it is the keyword 'in' without correcting once the third letter is typed)

**Comment by raichoo** [comment]
This has been pointed out a couple of times, sadly nobody could figure out what triggers this behavior. I'm leaving this open hoping that someone has an idea.

**Comment by raichoo** [comment]
Please check PR #63 it refactors indentation among other things. This should be fixed in there.
