### ISSUE TITLE
plugin clobbers my format option

### ISSUE THREAD

**Issue by aspidites** [neovimhaskell/haskell-vim#60]
I just spent an hour trying to find out why comments weren't automatically wrapping at text width, as I had `set formatoptions+=t` in my './config/nvim/init.vim'. Turns out this plug is [changing](https://github.com/neovimhaskell/haskell-vim/blob/master/after/ftplugin/haskell.vim#L2) my format options. While I don't see t in there explicitly, it certainly seems to be the case that for Haskell files this functionality breaks and `:verbose set fo?` tells me this plugin is the last thing to touch that option. Commenting out the offending line restores functionality.

As such, I'm wondering if there is a legitimate reason to set this from the plugin?

While I could add an `after/ftplugin/haskell.vim` file to my config, I'd prefer that my plugins didn't hijack my settings at all.

**Comment by mitchellwrosen** [comment]
+1, the hard-coded `formatoptions-=cro` is very irritating. Just spent an hour tracking this down.

**Comment by raichoo** [comment]
These settings have been there for historical reasons. Looks like the problems they dealt with have been fixed. I'm removing these for now.
