### ISSUE TITLE
Indenting Record Syntax

### ISSUE THREAD

**Issue by panthomakos** [neovimhaskell/haskell-vim#61]
The following is not properly indented:

```
data Customer = Customer
{ customerID      :: CustomerID
, customerName    :: String
, customerAddress :: Address
} deriving (Show)
```

The resulting code should look like this:

```
data Customer = Customer
    { customerID      :: CustomerID
    , customerName    :: String
    , customerAddress :: Address
    } deriving (Show)
```

Instead the `{}` part is not modified (or if it is already indented, the indentation is removed).

**Comment by raichoo** [comment]
Please check PR #63 it refactors indentation among other things. This should be fixed in there.

**Comment by panthomakos** [comment]
Pulled from master and it works.

:+1:
