### ISSUE TITLE
Strange indentation around braces

### ISSUE THREAD

**Issue by parsonsmatt** [neovimhaskell/haskell-vim#64]
Suppose you prefer to lay data declarations out like:

```haskell
data Foo
    = Foo
    { foo :: Int
    , bar :: Char
    , baz :: Int
    } deriving (Eq, Ord)
```

Attempting to input the above in a Haskell buffer with only `haskell-vim` loaded gives the following:

```haskell
data Foo
    = Foo
        { foo :: Int
            , bar :: Char
            , baz :: Int
        } deriving (Eq, Ord)
```

The braces consistently align themselves, but the commas are always indented exactly one time.

Any idea how I might configure `haskell-vim` to not do that, or what part of the code might be causing that indentation?

**Comment by raichoo** [comment]
I think there are some problems with the current setup of `indentkeys`. I'm using less aggressive rules now. I had some issues with this myself, lets see how this works.

**Comment by parsonsmatt** [comment]
I'm still getting this after pulling the master branch on an. Output of indentation is:

```haskell
data Foo a
    = Foo
        { foo :: Int
            , bar :: String
            , baz :: Bool
        }
```

**Comment by raichoo** [comment]
I can't reproduce this anymore.
