### ISSUE TITLE
indentation error on 'case...of...'

### ISSUE THREAD

**Issue by jiajunhuang** [neovimhaskell/haskell-vim#65]
hi, I'm reading `Real World Haskell`, and I'm using this script to help me handle the indent.

But I've got an issue at line 8 :

```haskell
splitLines [] = []
splitLines cs =
    let (pre, suf) = break isTerminator cs
     in pre: case suf of
               ('\r': '\n': rest) -> splitLines rest
               ('\r': rest) -> splitLines rest
               ('\n': rest) -> splitLines rest
             _ -> []

isTerminator c = c == '\r' || c == '\n'
```

`_ -> []` is in a bad indent level.

Thanks!

**Comment by raichoo** [comment]
I tried to indent the alternatives, which might be a dumb idea. I removed this. It hopefully works as expected now.

**Comment by jiajunhuang** [comment]
:+1: thank you very much.
