### ISSUE TITLE
Re-indenting lines already containing text

### ISSUE THREAD

**Issue by jonascarpay** [neovimhaskell/haskell-vim#76]
Is there a way to stop the re-indentation of lines already containing text? Problems occur after manually fixing ambiguities. For example, after manually fixing the indentation for
```haskell
where foo = do do1
               do2
```
adding a space after do2 turns it into
```haskell
where foo = do do1
      do2 <- ...
```

**Comment by raichoo** [comment]
Looks like the indentation precedence was not right for `where` blocks. Please try again.

**Comment by jonascarpay** [comment]
Thanks for the quick response. I'm getting correct indentation for `do`! But it looks like `where` no longer indents :/
```haskell
foo = bar
where bar = do do1
               do2 =
```

**Comment by raichoo** [comment]
Arg, looks like there was a missing `endif` somewhere in the code which was silently ignored. Gotta love VimL.

**Comment by jonascarpay** [comment]
Indentation on where block now works correctly 👍. There are other places where I'm having trouble with the automatic re-indentation that I suspect might not just be a bug, but ambiguities in indentation? For example:
After manually fixing 
```haskell
foo = do do1
         let var1 = undefined
             do2
```
to
```haskell
foo = do do1
         let var1 = undefined
         do2
```
typing a space after `do2` re-indents it to
```haskell
foo = do do1
         let var1 = undefined
             do2 var1
```

**Comment by raichoo** [comment]
Yep, that's somewhat hard to disambiguate because you could write something like:

```
foo = do do1
         let var1 = undefined
             do2 var1
          in …
```

**Comment by jonascarpay** [comment]
I don't think I made the issue entirely clear. I'll see if I can record a quick demonstration tonight!

**Comment by raichoo** [comment]
You've made the issue clear. The thing is that with the tools that Vim has to offer this is pretty hard to do. And it's not efficient, I've elaborated this in several issue reports.

**Comment by bounceme** [comment]
https://github.com/neovimhaskell/haskell-vim/blob/master/indent/haskell.vim#L61
change this to not include `space`, might improve this plugin to remove that( assuming it isn't completely necessary for something)

**Comment by raichoo** [comment]
This won't fix the problem of wrong indentation. It would only defer the wrong indentation to a later point in time.

**Comment by bounceme** [comment]
true, though it is less of a problem when you can type a space and not need to again manually reindent

**Comment by jonascarpay** [comment]
Do you think it's feasible to have Ctrl-D or < work by snapping to either 1) possible indentations suggested by the syntax or 2) the same indentation levels as nearby lines? I might give nr 2 a shot over the weekend if there's no reason why it shouldn't work, but it sounds like there might be some pitfalls.

Also, sorry for reopening and closing the issue, that was not on purpose.

**Comment by raichoo** [comment]
I'm not entirely sure what you are trying to do, so I can't tell if it makes sense or if I would even merge it :)
