### ISSUE TITLE
Disabling case et alii alignment

### ISSUE THREAD

**Issue by moll** [neovimhaskell/haskell-vim#83]
Hey,

An otherwise nice syntax and indenting plugin, but I'm not a fan of the `case` clause indenting aligning it with the `case` keyword on the previous line. Would it be possible to make this and other similar settings configurable to disable the alignment and just leave it with a n-character indent?

Personally, I've found alignments waste precious horizontal space from 80 columns. ^_^

Thanks!

**Comment by raichoo** [comment]
Indentation has always been configurable you can edit the `let g:haskell_indent_case = 2` settings. If that's what you are looking for.

**Comment by moll** [comment]
While further indent depth is configurable, Haskell.vim does indent _aligning_ like I describe above. That isn't configurable. :-)

**Comment by raichoo** [comment]
Ah I see, try to set `let g:haskell_indent_case_alternative = 1`. I've just added this.

**Comment by moll** [comment]
I'll give it a try. Thank you!
