### ISSUE TITLE
Feature Request: command that echos type

### ISSUE THREAD

**Issue by CallumHoward** [neovimhaskell/haskell-vim#84]
Could we have a command that echos the current type as seen [here](https://github.com/eagletmt/ghcmod-vim#ghcmodtype-ghcmodtypeclear)?

**Comment by raichoo** [comment]
Why not just use the `ghc-mod` plugin? That's what I'm doing.

**Comment by CallumHoward** [comment]
@raichoo You got me there, that's a good point. I guess I already have neomake, and so I wanted to avoid doubling up and loading more plugins than I must. When I get some time to configure it, I'll give it a try.
