### ISSUE TITLE
Where indentation doesn't seem to use configuration value 

### ISSUE THREAD

**Issue by owst** [neovimhaskell/haskell-vim#9]
I like to indent the "where" keyword by 2 spaces from the expression it is contained within, and then indent the bindings in the where (on a newline) by 2 *more* spaces, so the bindings are indented 4 spaces from the expression containing them, thus:

    foop = doop 1
      where 
        doop x = x + woop x
        woop x = 0

However, when I hit enter after `doop 1` and type where, it correctly gets indented by 2 spaces (I don't think this is configurable, looking at the README?) but then after hitting enter and typing `doop x` and `woop x`, the indentation is as follows:

    foop = doop 1
      where 
          doop x = x + woop x
          woop x = 0

I have set `let g:haskell_indent_where = 2` in my .vimrc, but it doesn't appear to have any effect.

**Comment by raichoo** [comment]
I'm not able to reproduce this with the current version of haskell-vim. Is this still happening for you?

**Comment by owst** [comment]
Yes, it still happens for me. I have just updated using vundle and still have the same behaviour.

I typed the following to reproduce (CR = carriage return):

"f = g 1" CR "where" CR "g x = x" CR "h x = x"

which gave:

```
f = g 1
  where
      g x = x
      h x = x
```

However, "f = g 1" CR "where g x = x" CR "h x = x" gives, which seems to be correct.

```
f = g 1
  where g x = x
    h x = x
```

Ideally, I'd like the first example to look like:

```
f = g 1
  where
    g x = x
    h x = x
```

Furthermore, it seems the indentation is taken from the RHS expression rather than the LHS; without any manual indentation I got this:

```
thisIsALongFunctionName withSome longArguments =
    theRHSFunction withSome
      where
          theRHSFunction x = x
``` 

ideally I'd want it to look like:

```
thisIsALongFunctionName withSome longArguments =
    theRHSFunction withSome
  where
    theRHSFunction x = x
```

**Comment by raichoo** [comment]
That would be pretty hard to realize with the tools vim gives you. It would certainly work in some cases but would break others. If you really want that I'd say "patches welcome".

**Comment by johntyree** [comment]
@owst I'd also point out that those are *different* things. In the example you gave, the where clause is defining things at the top level of the function, whereas I think the plugin is defining them within the scope of `theRHSFunction withSome`.
