### ISSUE TITLE
Wrong indent with list syntax

### ISSUE THREAD

**Issue by cloudhead** [neovimhaskell/haskell-vim#94]
I have a pretty basic case that doesn't work properly:

```haskell
foo :: [Int]
foo =
    [ 1
      , 2
      , 3
    ]
```
The lines with `2` and `3` are incorrectly auto-indented an extra two spaces. This seems to take place in the `indentGuard` function. Looking into it now but maybe you know how to fix it already.

**Comment by cloudhead** [comment]
Ok I think I found the problem. I'm not using the same syntax file, and since this is based on synIDs, such as `haskellBracket` etc. it doesn't work.

**Comment by raichoo** [comment]
So I guess I'll just close this then.
